name: example-firefox
on: push
jobs:
  firefox:
    runs-on: ubuntu-16.04
      # Cypress Docker image with Chrome v78
      # and Firefox v70 pre-installed
      container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: yarn
      - name: Percy Test
        uses: percy/exec-action@v0.3.0
        with:
          command: "cypress run --browser chrome"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}